### ISSUE TITLE
番剧api里没有时间吗

### ISSUE THREAD

**Issue by kirbystudy** [eventhorizonsky/ezanime-ui#1]

**Comment by eventhorizonsky** [comment]
弹弹的api吗，时间是指更新时间？

**Comment by kirbystudy** [comment]
https://api.dandanplay.net/api/v2/bangumi/shin?filterAdultContent=false
对的，这个api里没有更新时间。

**Comment by eventhorizonsky** [comment]
你可以参考https://api.dandanplay.net/swagger/ui/index 这个链接提供的api示例，实际上这是一个增加弹幕用的api，新番时间表只能返回是周几更新的，具体的时间是没有的

**Comment by kirbystudy** [comment]
好的。我去看看这里面的api 谢谢
